/*
* AUTOGENERATED FILE 
* DO NOT MODIFY MANUALLY!!!
*/
extern "C"{
    const char DESCRIPTION[255]  __attribute__((section(".metadata_pool")))= 
        "****************"  // placeholder for beggining
        "20251213T121238"   // DateTime using ISO-8601 format
        " "                 // alignment
        "c0d7a758"          // STLIB commit
        "--------"          // ADJ commit
        "52190b03"          // Board commit
        // the '=' is used for unparsing
        ;
}